"""Added media_type to gallery

Revision ID: 80720d9145ce
Revises: f1b6fd7382e9
Create Date: 2026-04-23 08:42:50.941845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80720d9145ce'
down_revision = 'f1b6fd7382e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expiry')

    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
